<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "--color --require features --format #{ENV['CUCUMBER_FORMAT'] || 'progress'} --strict --tags ~@wip"
%>
default: <%= std_opts %> features
wip: --require features --tags @wip:3 --wip features
rerun: <%= rerun_opts %> --require features --format rerun --out rerun.txt --strict --tags ~@wip
autotest: <%= std_opts %>
autotest-all: <%= std_opts %>
